import type { ArenaDef } from '../types';

export const COLOSSEUM: ArenaDef = {
  id: 'colosseum',
  nameKey: 'arenas.colosseum.name',
  descKey: 'arenas.colosseum.desc',
  size: { w: 1600, h: 1000 },
  theme: {
    floor: '#34302c',
    floorAlt: '#2a2724',
    wall: '#5e5246',
    accent: '#FFC21A',
    light: '#fff1cf',
    ambient: 0.5,
    mood: 'colosseum',
  },
  grip: 1,
  unlockAfter: 'c12',
  pits: [
    { rect: { x: 520, y: 435, w: 120, h: 130 }, opensAt: 40 },
    { rect: { x: 960, y: 435, w: 120, h: 130 }, opensAt: 85, button: { x: 770, y: 40, w: 60, h: 60 } },
  ],
  houseRobots: [
    {
      id: 'warden',
      nameKey: 'house.warden',
      zone: { x: 0, y: 0, w: 190, h: 190 },
      attack: 'hammer',
      damage: 18,
      speed: 160,
      attackCooldown: 1.5,
      grace: 1.0,
      color: '#d9a400',
    },
    {
      id: 'reaper',
      nameKey: 'house.reaper',
      zone: { x: 1410, y: 810, w: 190, h: 190 },
      attack: 'saw',
      damage: 22,
      speed: 160,
      attackCooldown: 1.2,
      grace: 1.0,
      color: '#b02a2a',
    },
  ],
  hazards: [
    {
      kind: 'floorFlipper',
      id: 'ff1',
      rect: { x: 760, y: 180, w: 80, h: 80 },
      launch: 820,
      damage: 6,
      period: 6,
      telegraph: 0.9,
      active: 0.3,
      randomPhase: true,
    },
    {
      kind: 'floorFlipper',
      id: 'ff2',
      rect: { x: 760, y: 740, w: 80, h: 80 },
      launch: 820,
      damage: 6,
      period: 6,
      telegraph: 0.9,
      active: 0.3,
      phase: 3,
      randomPhase: true,
    },
    {
      kind: 'wallSaw',
      id: 'ws1',
      rect: { x: 300, y: 0, w: 160, h: 26 },
      dps: 30,
      period: 5,
      telegraph: 0.8,
      active: 2,
      randomPhase: true,
    },
    {
      kind: 'wallSaw',
      id: 'ws2',
      rect: { x: 1140, y: 0, w: 160, h: 26 },
      dps: 30,
      period: 5,
      telegraph: 0.8,
      active: 2,
      phase: 2.5,
      randomPhase: true,
    },
    {
      kind: 'wallSaw',
      id: 'ws3',
      rect: { x: 300, y: 974, w: 160, h: 26 },
      dps: 30,
      period: 5,
      telegraph: 0.8,
      active: 2,
      phase: 1.2,
      randomPhase: true,
    },
    {
      kind: 'wallSaw',
      id: 'ws4',
      rect: { x: 1140, y: 974, w: 160, h: 26 },
      dps: 30,
      period: 5,
      telegraph: 0.8,
      active: 2,
      phase: 3.7,
      randomPhase: true,
    },
    {
      kind: 'spikes',
      id: 'csp1',
      rect: { x: 330, y: 300, w: 90, h: 90 },
      damage: 14,
      launch: 300,
      period: 5.5,
      telegraph: 0.9,
      active: 0.8,
      until: 70,
      randomPhase: true,
    },
    {
      kind: 'spikes',
      id: 'csp2',
      rect: { x: 1180, y: 610, w: 90, h: 90 },
      damage: 14,
      launch: 300,
      period: 5.5,
      telegraph: 0.9,
      active: 0.8,
      until: 70,
      randomPhase: true,
    },
    {
      kind: 'flameJet',
      id: 'cf1',
      circle: { x: 380, y: 650, r: 50 },
      dps: 26,
      burn: 2,
      period: 6,
      telegraph: 1.1,
      active: 1.4,
      from: 60,
      randomPhase: true,
    },
    {
      kind: 'flameJet',
      id: 'cf2',
      circle: { x: 1220, y: 350, r: 50 },
      dps: 26,
      burn: 2,
      period: 6,
      telegraph: 1.1,
      active: 1.4,
      from: 60,
      randomPhase: true,
    },
    {
      kind: 'press',
      id: 'cpress',
      rect: { x: 730, y: 430, w: 140, h: 140 },
      damage: 40,
      stun: 1,
      period: 7,
      telegraph: 1.5,
      active: 0.6,
      from: 100,
      randomPhase: true,
    },
  ],
  spawns: [
    { x: 260, y: 500, angle: 0 },
    { x: 1340, y: 500, angle: Math.PI },
    { x: 1340, y: 330, angle: Math.PI },
  ],
};
