import type { ArenaDef } from '../types';

export const FOUNDRY: ArenaDef = {
  id: 'foundry',
  nameKey: 'arenas.foundry.name',
  descKey: 'arenas.foundry.desc',
  size: { w: 1300, h: 850 },
  theme: {
    floor: '#2d2622',
    floorAlt: '#241d1a',
    wall: '#4a2f22',
    accent: '#FF5A1F',
    light: '#ff9a52',
    ambient: 0.55,
    mood: 'foundry',
  },
  grip: 1,
  unlockAfter: 'c04',
  pits: [{ rect: { x: 585, y: 120, w: 130, h: 130 }, opensAt: 55, button: { x: 1200, y: 40, w: 60, h: 60 } }],
  houseRobots: [
    {
      id: 'furnace',
      nameKey: 'house.furnace',
      zone: { x: 0, y: 0, w: 180, h: 180 },
      attack: 'flame',
      damage: 18,
      speed: 140,
      attackCooldown: 1.4,
      grace: 1.2,
      color: '#c43d12',
    },
  ],
  hazards: [
    { kind: 'lava', id: 'lava', rect: { x: 0, y: 780, w: 1300, h: 70 }, dps: 20 },
    {
      kind: 'flameJet',
      id: 'f1',
      circle: { x: 380, y: 300, r: 48 },
      dps: 24,
      burn: 2,
      period: 7,
      telegraph: 1.2,
      active: 1.4,
      randomPhase: true,
    },
    {
      kind: 'flameJet',
      id: 'f2',
      circle: { x: 920, y: 300, r: 48 },
      dps: 24,
      burn: 2,
      period: 7,
      telegraph: 1.2,
      active: 1.4,
      phase: 3.5,
      randomPhase: true,
    },
    {
      kind: 'flameJet',
      id: 'f3',
      circle: { x: 650, y: 560, r: 54 },
      dps: 24,
      burn: 2,
      period: 8,
      telegraph: 1.2,
      active: 1.6,
      phase: 1.5,
      randomPhase: true,
    },
  ],
  spawns: [
    { x: 230, y: 470, angle: 0 },
    { x: 1070, y: 470, angle: Math.PI },
    { x: 1070, y: 300, angle: Math.PI },
  ],
};
